# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gamestore_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Carga automatica de datos de prueba (solo si las tablas estan vacias, ver DataLoader)
spring.sql.init.mode=never

server.port=8080
